/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteHomeRouteImport } from './routes/site.home'
import { Route as SiteContactRouteImport } from './routes/site.contact'
import { Route as SiteAboutRouteImport } from './routes/site.about'
import { Route as HireTokenRouteImport } from './routes/hire.$token'
import { Route as CareersIdRouteImport } from './routes/careers.$id'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppOutreachRouteImport } from './routes/_app/outreach'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppDistributionRouteImport } from './routes/_app/distribution'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppCandidatesRouteImport } from './routes/_app/candidates'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppJobsIndexRouteImport } from './routes/_app/jobs.index'
import { Route as CareersTrackTokenRouteImport } from './routes/careers.track.$token'
import { Route as AppSettingsDistributionRouteImport } from './routes/_app/settings_.distribution'
import { Route as AppProjectsIdRouteImport } from './routes/_app/projects.$id'
import { Route as AppOutreachNewRouteImport } from './routes/_app/outreach.new'
import { Route as AppOutreachIdRouteImport } from './routes/_app/outreach.$id'
import { Route as AppJobsNewRouteImport } from './routes/_app/jobs.new'
import { Route as AppJobsIdRouteImport } from './routes/_app/jobs.$id'
import { Route as AppClientsIdRouteImport } from './routes/_app/clients.$id'
import { Route as AppCandidatesIdRouteImport } from './routes/_app/candidates.$id'
import { Route as AppProjectsIdParseRouteImport } from './routes/_app/projects.$id.parse'
import { Route as AppJobsIdParseRouteImport } from './routes/_app/jobs.$id.parse'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteHomeRoute = SiteHomeRouteImport.update({
  id: '/site/home',
  path: '/site/home',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/site/contact',
  path: '/site/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/site/about',
  path: '/site/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HireTokenRoute = HireTokenRouteImport.update({
  id: '/hire/$token',
  path: '/hire/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIdRoute = CareersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CareersRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachRoute = AppOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributionRoute = AppDistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesRoute = AppCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const CareersTrackTokenRoute = CareersTrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => CareersRoute,
} as any)
const AppSettingsDistributionRoute = AppSettingsDistributionRouteImport.update({
  id: '/settings_/distribution',
  path: '/settings/distribution',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppOutreachNewRoute = AppOutreachNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppOutreachRoute,
} as any)
const AppOutreachIdRoute = AppOutreachIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOutreachRoute,
} as any)
const AppJobsNewRoute = AppJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppCandidatesIdRoute = AppCandidatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCandidatesRoute,
} as any)
const AppProjectsIdParseRoute = AppProjectsIdParseRouteImport.update({
  id: '/parse',
  path: '/parse',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppJobsIdParseRoute = AppJobsIdParseRouteImport.update({
  id: '/parse',
  path: '/parse',
  getParentRoute: () => AppJobsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRouteWithChildren
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AppAnalyticsRoute
  '/approvals': typeof AppApprovalsRoute
  '/candidates': typeof AppCandidatesRouteWithChildren
  '/clients': typeof AppClientsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/distribution': typeof AppDistributionRoute
  '/inbox': typeof AppInboxRoute
  '/outreach': typeof AppOutreachRouteWithChildren
  '/projects': typeof AppProjectsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/careers/$id': typeof CareersIdRoute
  '/hire/$token': typeof HireTokenRoute
  '/site/about': typeof SiteAboutRoute
  '/site/contact': typeof SiteContactRoute
  '/site/home': typeof SiteHomeRoute
  '/candidates/$id': typeof AppCandidatesIdRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/jobs/$id': typeof AppJobsIdRouteWithChildren
  '/jobs/new': typeof AppJobsNewRoute
  '/outreach/$id': typeof AppOutreachIdRoute
  '/outreach/new': typeof AppOutreachNewRoute
  '/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/settings/distribution': typeof AppSettingsDistributionRoute
  '/careers/track/$token': typeof CareersTrackTokenRoute
  '/jobs/': typeof AppJobsIndexRoute
  '/jobs/$id/parse': typeof AppJobsIdParseRoute
  '/projects/$id/parse': typeof AppProjectsIdParseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRouteWithChildren
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AppAnalyticsRoute
  '/approvals': typeof AppApprovalsRoute
  '/candidates': typeof AppCandidatesRouteWithChildren
  '/clients': typeof AppClientsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/distribution': typeof AppDistributionRoute
  '/inbox': typeof AppInboxRoute
  '/outreach': typeof AppOutreachRouteWithChildren
  '/projects': typeof AppProjectsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/careers/$id': typeof CareersIdRoute
  '/hire/$token': typeof HireTokenRoute
  '/site/about': typeof SiteAboutRoute
  '/site/contact': typeof SiteContactRoute
  '/site/home': typeof SiteHomeRoute
  '/candidates/$id': typeof AppCandidatesIdRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/jobs/$id': typeof AppJobsIdRouteWithChildren
  '/jobs/new': typeof AppJobsNewRoute
  '/outreach/$id': typeof AppOutreachIdRoute
  '/outreach/new': typeof AppOutreachNewRoute
  '/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/settings/distribution': typeof AppSettingsDistributionRoute
  '/careers/track/$token': typeof CareersTrackTokenRoute
  '/jobs': typeof AppJobsIndexRoute
  '/jobs/$id/parse': typeof AppJobsIdParseRoute
  '/projects/$id/parse': typeof AppProjectsIdParseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/careers': typeof CareersRouteWithChildren
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/signup': typeof SignupRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/candidates': typeof AppCandidatesRouteWithChildren
  '/_app/clients': typeof AppClientsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/distribution': typeof AppDistributionRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/outreach': typeof AppOutreachRouteWithChildren
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/careers/$id': typeof CareersIdRoute
  '/hire/$token': typeof HireTokenRoute
  '/site/about': typeof SiteAboutRoute
  '/site/contact': typeof SiteContactRoute
  '/site/home': typeof SiteHomeRoute
  '/_app/candidates/$id': typeof AppCandidatesIdRoute
  '/_app/clients/$id': typeof AppClientsIdRoute
  '/_app/jobs/$id': typeof AppJobsIdRouteWithChildren
  '/_app/jobs/new': typeof AppJobsNewRoute
  '/_app/outreach/$id': typeof AppOutreachIdRoute
  '/_app/outreach/new': typeof AppOutreachNewRoute
  '/_app/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/_app/settings_/distribution': typeof AppSettingsDistributionRoute
  '/careers/track/$token': typeof CareersTrackTokenRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
  '/_app/jobs/$id/parse': typeof AppJobsIdParseRoute
  '/_app/projects/$id/parse': typeof AppProjectsIdParseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/login'
    | '/marketing'
    | '/signup'
    | '/analytics'
    | '/approvals'
    | '/candidates'
    | '/clients'
    | '/dashboard'
    | '/distribution'
    | '/inbox'
    | '/outreach'
    | '/projects'
    | '/settings'
    | '/careers/$id'
    | '/hire/$token'
    | '/site/about'
    | '/site/contact'
    | '/site/home'
    | '/candidates/$id'
    | '/clients/$id'
    | '/jobs/$id'
    | '/jobs/new'
    | '/outreach/$id'
    | '/outreach/new'
    | '/projects/$id'
    | '/settings/distribution'
    | '/careers/track/$token'
    | '/jobs/'
    | '/jobs/$id/parse'
    | '/projects/$id/parse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/login'
    | '/marketing'
    | '/signup'
    | '/analytics'
    | '/approvals'
    | '/candidates'
    | '/clients'
    | '/dashboard'
    | '/distribution'
    | '/inbox'
    | '/outreach'
    | '/projects'
    | '/settings'
    | '/careers/$id'
    | '/hire/$token'
    | '/site/about'
    | '/site/contact'
    | '/site/home'
    | '/candidates/$id'
    | '/clients/$id'
    | '/jobs/$id'
    | '/jobs/new'
    | '/outreach/$id'
    | '/outreach/new'
    | '/projects/$id'
    | '/settings/distribution'
    | '/careers/track/$token'
    | '/jobs'
    | '/jobs/$id/parse'
    | '/projects/$id/parse'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/careers'
    | '/login'
    | '/marketing'
    | '/signup'
    | '/_app/analytics'
    | '/_app/approvals'
    | '/_app/candidates'
    | '/_app/clients'
    | '/_app/dashboard'
    | '/_app/distribution'
    | '/_app/inbox'
    | '/_app/outreach'
    | '/_app/projects'
    | '/_app/settings'
    | '/careers/$id'
    | '/hire/$token'
    | '/site/about'
    | '/site/contact'
    | '/site/home'
    | '/_app/candidates/$id'
    | '/_app/clients/$id'
    | '/_app/jobs/$id'
    | '/_app/jobs/new'
    | '/_app/outreach/$id'
    | '/_app/outreach/new'
    | '/_app/projects/$id'
    | '/_app/settings_/distribution'
    | '/careers/track/$token'
    | '/_app/jobs/'
    | '/_app/jobs/$id/parse'
    | '/_app/projects/$id/parse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CareersRoute: typeof CareersRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  SignupRoute: typeof SignupRoute
  HireTokenRoute: typeof HireTokenRoute
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteHomeRoute: typeof SiteHomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/home': {
      id: '/site/home'
      path: '/site/home'
      fullPath: '/site/home'
      preLoaderRoute: typeof SiteHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/contact': {
      id: '/site/contact'
      path: '/site/contact'
      fullPath: '/site/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/about': {
      id: '/site/about'
      path: '/site/about'
      fullPath: '/site/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/$token': {
      id: '/hire/$token'
      path: '/hire/$token'
      fullPath: '/hire/$token'
      preLoaderRoute: typeof HireTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$id': {
      id: '/careers/$id'
      path: '/$id'
      fullPath: '/careers/$id'
      preLoaderRoute: typeof CareersIdRouteImport
      parentRoute: typeof CareersRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach': {
      id: '/_app/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AppOutreachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/distribution': {
      id: '/_app/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof AppDistributionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates': {
      id: '/_app/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AppCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/careers/track/$token': {
      id: '/careers/track/$token'
      path: '/track/$token'
      fullPath: '/careers/track/$token'
      preLoaderRoute: typeof CareersTrackTokenRouteImport
      parentRoute: typeof CareersRoute
    }
    '/_app/settings_/distribution': {
      id: '/_app/settings_/distribution'
      path: '/settings/distribution'
      fullPath: '/settings/distribution'
      preLoaderRoute: typeof AppSettingsDistributionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/outreach/new': {
      id: '/_app/outreach/new'
      path: '/new'
      fullPath: '/outreach/new'
      preLoaderRoute: typeof AppOutreachNewRouteImport
      parentRoute: typeof AppOutreachRoute
    }
    '/_app/outreach/$id': {
      id: '/_app/outreach/$id'
      path: '/$id'
      fullPath: '/outreach/$id'
      preLoaderRoute: typeof AppOutreachIdRouteImport
      parentRoute: typeof AppOutreachRoute
    }
    '/_app/jobs/new': {
      id: '/_app/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AppJobsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$id': {
      id: '/_app/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$id': {
      id: '/_app/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/candidates/$id': {
      id: '/_app/candidates/$id'
      path: '/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AppCandidatesIdRouteImport
      parentRoute: typeof AppCandidatesRoute
    }
    '/_app/projects/$id/parse': {
      id: '/_app/projects/$id/parse'
      path: '/parse'
      fullPath: '/projects/$id/parse'
      preLoaderRoute: typeof AppProjectsIdParseRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/jobs/$id/parse': {
      id: '/_app/jobs/$id/parse'
      path: '/parse'
      fullPath: '/jobs/$id/parse'
      preLoaderRoute: typeof AppJobsIdParseRouteImport
      parentRoute: typeof AppJobsIdRoute
    }
  }
}

interface AppCandidatesRouteChildren {
  AppCandidatesIdRoute: typeof AppCandidatesIdRoute
}

const AppCandidatesRouteChildren: AppCandidatesRouteChildren = {
  AppCandidatesIdRoute: AppCandidatesIdRoute,
}

const AppCandidatesRouteWithChildren = AppCandidatesRoute._addFileChildren(
  AppCandidatesRouteChildren,
)

interface AppClientsRouteChildren {
  AppClientsIdRoute: typeof AppClientsIdRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsIdRoute: AppClientsIdRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppOutreachRouteChildren {
  AppOutreachIdRoute: typeof AppOutreachIdRoute
  AppOutreachNewRoute: typeof AppOutreachNewRoute
}

const AppOutreachRouteChildren: AppOutreachRouteChildren = {
  AppOutreachIdRoute: AppOutreachIdRoute,
  AppOutreachNewRoute: AppOutreachNewRoute,
}

const AppOutreachRouteWithChildren = AppOutreachRoute._addFileChildren(
  AppOutreachRouteChildren,
)

interface AppProjectsIdRouteChildren {
  AppProjectsIdParseRoute: typeof AppProjectsIdParseRoute
}

const AppProjectsIdRouteChildren: AppProjectsIdRouteChildren = {
  AppProjectsIdParseRoute: AppProjectsIdParseRoute,
}

const AppProjectsIdRouteWithChildren = AppProjectsIdRoute._addFileChildren(
  AppProjectsIdRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRouteWithChildren
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRouteWithChildren,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppJobsIdRouteChildren {
  AppJobsIdParseRoute: typeof AppJobsIdParseRoute
}

const AppJobsIdRouteChildren: AppJobsIdRouteChildren = {
  AppJobsIdParseRoute: AppJobsIdParseRoute,
}

const AppJobsIdRouteWithChildren = AppJobsIdRoute._addFileChildren(
  AppJobsIdRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppCandidatesRoute: typeof AppCandidatesRouteWithChildren
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDistributionRoute: typeof AppDistributionRoute
  AppInboxRoute: typeof AppInboxRoute
  AppOutreachRoute: typeof AppOutreachRouteWithChildren
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppJobsIdRoute: typeof AppJobsIdRouteWithChildren
  AppJobsNewRoute: typeof AppJobsNewRoute
  AppSettingsDistributionRoute: typeof AppSettingsDistributionRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppCandidatesRoute: AppCandidatesRouteWithChildren,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDistributionRoute: AppDistributionRoute,
  AppInboxRoute: AppInboxRoute,
  AppOutreachRoute: AppOutreachRouteWithChildren,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppJobsIdRoute: AppJobsIdRouteWithChildren,
  AppJobsNewRoute: AppJobsNewRoute,
  AppSettingsDistributionRoute: AppSettingsDistributionRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CareersRouteChildren {
  CareersIdRoute: typeof CareersIdRoute
  CareersTrackTokenRoute: typeof CareersTrackTokenRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersIdRoute: CareersIdRoute,
  CareersTrackTokenRoute: CareersTrackTokenRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CareersRoute: CareersRouteWithChildren,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  SignupRoute: SignupRoute,
  HireTokenRoute: HireTokenRoute,
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteHomeRoute: SiteHomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
